spring.security.oauth2.client.registration.google.client-id=475285316900-9okk5abi5tfhu5h64j7muknn97624ht6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email